INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (101, 0, 0, '1989');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (101, 1, 0, '1963');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (101, 2, 0, '1957');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (101, 3, 0, '2001');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (102, 0, 0, 'Achieng oneko');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (102, 1, 0, 'Fred Kubai');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (102, 2, 0, 'Bildad Kagia');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (102, 3, 0, 'Raila Odinga');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (103, 0, 0, 'George Saitoti');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (103, 1, 0, 'Moody Awori');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (103, 2, 0, 'Daniel Moi');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (103, 3, 0, 'Mwai Kibaki');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (104, 0, 0, '63');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (104, 1, 0, '100');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (104, 2, 0, '40');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (104, 3, 0, '427');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (105, 0, 0, 'Nairobi');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (105, 1, 0, 'Western');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (105, 2, 0, 'Coast');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (105, 3, 0, 'Nyanza');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (106, 0, 0, 'Hell\'s gate');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (106, 1, 0, 'Fort Jesus');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (106, 2, 0, 'Hyrax');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (106, 3, 0, 'Olorgessaile');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (107, 0, 0, 'Gedi ruins');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (107, 1, 0, 'Olduvai gorge.');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (107, 2, 0, 'Nairobi Museum.');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (107, 3, 0, 'Old town Mombasa.');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (108, 0, 0, 'Donald Johanson');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (108, 1, 0, 'Meave Leakey');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (108, 2, 0, 'Richard Leakey');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (108, 3, 0, 'Mary Leakey');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (109, 0, 0, 'Homo erectus');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (109, 1, 0, 'Homo habilis');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (109, 2, 0, 'Homo sapiens');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (109, 3, 0, 'Homo sapien sapien');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (110, 0, 0, 'Cow');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (110, 1, 0, 'Pig');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (110, 2, 0, 'Goat');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (110, 3, 0, 'Hen');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (111, 0, 0, '50000 years ago');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (111, 1, 0, '10000 years ago');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (111, 2, 0, '15000 years ago');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (111, 3, 0, '11000 years ago');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (112, 0, 0, '5000 years');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (112, 1, 0, '2000 years');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (112, 2, 0, '40000years');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (112, 3, 0, '25000 years');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (113, 0, 0, 'Learned how to create fire');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (113, 1, 0, 'Lived in settled communities.');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (113, 2, 0, 'Created Cave Art.');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (113, 3, 0, 'Lived in nomadic clans.');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (114, 0, 0, 'Tea');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (114, 1, 0, 'Flowers');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (114, 2, 0, 'Maize');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (114, 3, 0, 'Coffee');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (115, 0, 0, 'Dormant');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (115, 1, 0, 'Extinct');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (115, 2, 0, 'Active');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (115, 3, 0, 'Volcano');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (116, 0, 0, 'Fish');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (116, 1, 0, 'Salt');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (116, 2, 0, 'Flamingos');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (116, 3, 0, 'Ostrich');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (117, 0, 0, 'KANU');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (117, 1, 0, 'NARC');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (117, 2, 0, 'TNA');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (117, 3, 0, 'NASA');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (118, 0, 0, '350');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (118, 1, 0, '290');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (118, 2, 0, '130');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (118, 3, 0, '47');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (119, 0, 0, 'Ivory Coast');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (119, 1, 0, 'Sierra leone');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (119, 2, 0, '.Ghana');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (119, 3, 0, 'Nigeria');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (120, 0, 0, 'Eritrea');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (120, 1, 0, 'Mauritania');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (120, 2, 0, 'Malawi');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (120, 3, 0, 'Zambia');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (121, 0, 0, 'Wearing gloves');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (121, 1, 0, 'Never leaving the house');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (121, 2, 0, 'Wearing a mask over your mouth');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (121, 3, 0, 'Washing your hands frequently');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (122, 0, 0, 'Improved Self-esteem');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (122, 1, 0, 'Better health');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (122, 2, 0, 'Create a better perception of you');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (122, 3, 0, 'Look Good');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (123, 0, 0, 'Spoon');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (123, 1, 0, 'Handkerchief');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (123, 2, 0, 'Sufuria');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (123, 3, 0, 'Textbook');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (124, 0, 0, 'Mike Sonko');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (124, 1, 0, 'Sakaja');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (124, 2, 0, 'Hassan Joho');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (124, 3, 0, 'Ferdinand Waititu');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (125, 0, 0, 'Diamond platinum');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (125, 1, 0, 'Uhuru Kenyatta');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (125, 2, 0, 'Yoweri Museveni');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (125, 3, 0, 'Dangote');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (126, 0, 0, 'Kenya Broadcasting Cooperation');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (126, 1, 0, 'Kenya Breweries center');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (126, 2, 0, 'Kenya Berry Centre');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (126, 3, 0, 'Kenya broadcasting center');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (127, 0, 0, 'January 2019');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (127, 1, 0, 'December 2020');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (127, 2, 0, 'January 2020');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (127, 3, 0, 'December 2019');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (128, 0, 0, 'Air pollution');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (128, 1, 0, 'Overgrazing');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (128, 2, 0, 'Deforestation');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (128, 3, 0, 'Loss of vegetation cover?');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (129, 0, 0, 'Salt');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (129, 1, 0, 'Fish');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (129, 2, 0, 'Flamingo');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (129, 3, 0, 'Hot water');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (130, 0, 0, 'Soda as');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (130, 1, 0, 'Sand');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (130, 2, 0, 'Cement');
INSERT INTO shuga_lobbysrv.t_act_answer_option (que_id, op_key, agree_cun, content) VALUES (130, 3, 0, 'Chalk');